# Generated by Django 4.2.2 on 2024-06-29 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_noticia_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('miniserio', models.CharField(max_length=20)),
                ('foto', models.ImageField(upload_to='fotos/')),
            ],
        ),
    ]
