# Generated by Django 4.2.2 on 2024-06-29 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_coords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coords',
            new_name='Coord',
        ),
    ]
