# Generated by Django 4.2.2 on 2024-06-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_coords_coord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
