# Generated by Django 4.2.2 on 2024-06-29 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_coord_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coord',
            old_name='miniserio',
            new_name='descricao',
        ),
    ]
